spring:
  application:
    name: micro-service-turbine
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8005"
        username: dabai
        password: dabai2019

server:
  port: 8006

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    instance-id: micro-service-turbine
  client:
    security:
      basic:
        username: dabai
        password: dabai2019
    service-url:
      defaultZone: http://${eureka.client.security.basic.username}:${eureka.client.security.basic.password}@localhost:8000/eureka
    registry-fetch-interval-seconds: 5 # 提高Client端拉取Server的注册信息的频率

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file: /home/app/logs/${spring.application.name}/global/jingle-global.log

turbine:
  app-config: micro-service-consumer # 需要聚合的服务名称
  aggregator:
    cluster-config: "default" # 需要聚合的集群名称
  cluster-name-expression: new String('default')  # 集群名表达式